### ISSUE TITLE
Error while changing font of avatar panel

### ISSUE THREAD

**Issue by rebron1900** [ElvUI-Vanilla/ElvUI_AddOnSkins#4]
Message: Interface\AddOns\ElvUI_Config\NamePlates.lua:546: attempt to index global `ACD' (a nil value)
Time: 12/29/18 01:06:18
Count: 1
Stack: (tail call): ?
Interface\AddOns\ElvUI_Config\NamePlates.lua:546: in function <Interface\AddOns\ElvUI_Config\NamePlates.lua:546>
(tail call): ?
[C]: in function `xpcall'
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:825: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:644>
(tail call): ?
[C]: in function `xpcall'
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...Ons\ElvUI_Config\Libraries\AceGUI-3.0\AceGUI-3.0.lua:328: in function `Fire'
...ies\AceGUI-3.0\widgets\AceGUIWidget-Button-ElvUI.lua:82: in function <...ies\AceGUI-3.0\widgets\AceGUIWidget-Button-ElvUI.lua:79>
Interface\AddOns\!Compatibility\api\wowAPI.lua:93: in function <Interface\AddOns\!Compatibility\api\wowAPI.lua:92>

**Comment by rebron1900** [comment]
chinese Client

**Comment by Crumdidlyumshis** [comment]
Weird I swere I just fixed this not long ago. I’ll look into it later when I’m home

**Comment by rebron1900** [comment]
thks, I hope fix it earlier!
Please tell me when it is time.

**Comment by rebron1900** [comment]
i trying download laster version,
Now it's ok.
------
New version elvui(8.0) plugin can runing on valine verison?

**Comment by Crumdidlyumshis** [comment]
No only use vanilla ElvUI for 1.12.1. Retail version will not work.
